- name: Deploy edxapp
  hosts: all
  become: True
  gather_facts: True
  vars:
    serial_count: 1
    CLUSTER_NAME: 'edxapp'
    CREATE_GRADES_AZURE_CONTAINER: "{{ azure_grades_blobstorage_create|default (no) }}"
    GRADE_STORAGE_TYPE: "{{ EDXAPP_GRADE_STORAGE_TYPE | default('local') }}"
  serial: "{{ serial_count }}"
  roles:
   - aws
   - role: automated
     AUTOMATED_USERS: "{{ EDXAPP_AUTOMATED_USERS | default({}) }}"
   - role: nginx
     nginx_sites:
     - lms
     - cms
     nginx_default_sites:
     - lms
     nginx_extra_sites: "{{ NGINX_EDXAPP_EXTRA_SITES }}"
     nginx_extra_configs: "{{ NGINX_EDXAPP_EXTRA_CONFIGS }}"
     nginx_redirects: "{{ NGINX_EDXAPP_CUSTOM_REDIRECTS }}"
   - { role: azure-blob-create,
       when: (GRADE_STORAGE_TYPE == 'azure' and CREATE_GRADES_AZURE_CONTAINER)
     }
   - configure-backups 
   - edxapp
   - role: datadog
     when: COMMON_ENABLE_DATADOG
   - role: splunkforwarder
     when: COMMON_ENABLE_SPLUNKFORWARDER
   - role: newrelic
     when: COMMON_ENABLE_NEWRELIC
   - role: newrelic_infrastructure
     when: COMMON_ENABLE_NEWRELIC_INFRASTRUCTURE
   - role: minos
     when: COMMON_ENABLE_MINOS
