# Configure a Jenkins master instance for testeng
# This has the Jenkins Java app, but none of the requirements
# to run the tests.

- name: Configure instance(s)
  hosts: all
  become: True
  gather_facts: True
  vars:
    COMMON_DATA_DIR: "/mnt2"
    COMMON_ENABLE_DATADOG: False
    COMMON_ENABLE_SPLUNKFORWARDER: False
    COMMON_SECURITY_UPDATES: yes
    SECURITY_UPGRADE_ON_ANSIBLE: true
    
  roles:
    - jenkins_master
