# Configure a Jenkins worker instance
# This has all the requirements to run test jobs,
# but not the Jenkins Java app.

- name: Configure instance(s)
  hosts: all
  become: True
  gather_facts: True
  vars:
    mongo_enable_journal: False
    serial_count: 1
    platform_worker: True
    COMMON_SECURITY_UPDATES: yes
    SECURITY_UPGRADE_ON_ANSIBLE: true
  serial: "{{ serial_count }}"
  roles:
    - browsers
    - browsermob-proxy
    - jenkins_worker
