---
- name: configure logrotate
  template: 
    src: logrotate.j2
    dest: /etc/logrotate.d/ec2_snapshot
    owner: root
    group: root
    mode: 0644
  become_method: sudo
  become: yes
  become_user: root

