---
- name: ensure {{ COMMON_APP_DIR }}/{{ olga_service_name }} dir exist
  file:
    path: "{{ COMMON_APP_DIR }}/{{ olga_service_name }}"
    owner: "{{ common_web_user }}"
    group: "{{ common_web_user }}"
    state: directory
  become_user: root
  become: true
  become_method: sudo

- name: write supervisor config
  template:
    src: "edx/app/supervisor/conf.d.available/olga.conf.j2"
    dest: "{{ supervisor_available_dir }}/{{ olga_service_name }}.conf"
    mode: 0650
    owner: "{{ supervisor_user }}"
    group: "{{ common_web_user }}"
  tags:
    - install
    - install:configuration

- name: enable supervisor script
  file:
    src: "{{ supervisor_available_dir }}/{{ olga_service_name }}.conf"
    dest: "{{ supervisor_cfg_dir }}/{{ olga_service_name }}.conf"
    state: link
    force: yes
  when: not disable_edx_services
  tags:
    - install
    - install:configuration

- name: update supervisor configuration
  shell: "{{ supervisor_ctl }} -c {{ supervisor_cfg }} update"
  when: not disable_edx_services
  tags:
    - manage
    - manage:start

- name: restart the application
  supervisorctl:
    state: restarted
    supervisorctl_path: "{{ supervisor_ctl }}"
    config: "{{ supervisor_cfg }}"
    name: "{{ olga_service_name }}"
  when: not disable_edx_services
  become_user: "{{ supervisor_service_user }}"
  tags:
    - manage
    - manage:start

