---
jenkins_user: "jenkins"
jenkins_group: "jenkins"
jenkins_home: /home/jenkins

jenkins_edx_platform_repo: https://github.com/raccoongang/edx-platform.git
jenkins_edx_platform_version: hetmantsev-hawthorn-ci-compare

# System packages
jenkins_debian_pkgs:
    - pkg-config
    - libffi-dev
    - python-dev
    - libsqlite3-dev
    - libfreetype6-dev

# packer direct download URL
packer_url: "https://releases.hashicorp.com/packer/0.8.6/packer_0.8.6_linux_amd64.zip"
