- name: Deploy all hadoop service configurations to a single node 
  hosts: all
  become: True
  gather_facts: True
  pre_tasks:
    - include_vars: edx-insights-override-defaults.yml
  roles:
    - role: common_vars
      when: edx_insights_some_undefined_variable_to_skip_role is defined
    - role: hadoop_common
      when: edx_insights_some_undefined_variable_to_skip_role is defined
    - role: analytics_api
      when: edx_insights_some_undefined_variable_to_skip_role is defined
    - role: insights
      when: edx_insights_some_undefined_variable_to_skip_role is defined
    - role: nginx
      when: edx_insights_some_undefined_variable_to_skip_role is defined
    - role: insights-letsencrypt
      NGINX_REDIRECT_TO_HTTPS: True
      nginx_sites:
        - hadoop
      nginx_default_sites:
        - hadoop
      nginx_skip_domains: [ "{{ INSIGHTS_BASE }}", "{{ ANALYTICS_API_BASE }}" ]
      when: INSIGHTS_USE_LETSENCRYPT|lower == 'yes'
    - insights-app-config
    - analytics_api-app-config
    - hadoop_config 
