---
- name: Create tracking logs upload playbook
  hosts: localhost
  become: True
  gather_facts: True
  pre_tasks:
    - include_vars: edx-insights-override-defaults.yml
  roles:
    - role: common_vars
      when: edx_insights_some_undefined_variable_to_skip_role is defined
    - role: edxapp
      when: edx_insights_some_undefined_variable_to_skip_role is defined
    - role: hadoop_common
      when: edx_insights_some_undefined_variable_to_skip_role is defined
    - role: hadoop_config
      when: edx_insights_some_undefined_variable_to_skip_role is defined
    - role: tracking-log-hdfs-upload-job

