#ansible-playbook -i ",localhost" -c local -e@/edx/app/edx_ansible/server-vars.yml /edx/app/edx_ansible/edx_ansible/playbooks/edx-credentials.yml
---
- hosts: localhost
  become: true
  gather_facts: True
  pre_tasks:
    - name: prepare install nodejs
      shell: curl -sL https://deb.nodesource.com/setup | sudo bash -

    - name: Update repositories cache and install packages
      apt:
        name: "{{ item }}"
        update_cache: yes
      with_items:
        - python-pip
        - libffi-dev
        - gcc
        - g++
        - build-essential
        - nodejs

  roles:
    - role: nginx
      nginx_sites:
      - credentials
    - credentials

