---
- hosts: all
  gather_facts: True
  tasks:
    - name: Update expired rabbitmq repo key
      shell: "curl -L https://packagecloud.io/rabbitmq/rabbitmq-server/gpgkey | apt-key add -"
      args:
        warn: False
      become: True

    - name: Update expired edX PPA repo key
      shell: "apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 69464050"
      args:
        warn: False
      become: True