---

# Example sandbox configuration
# for single server community
# installs

- name: Bootstrap instance(s)
  hosts: all
  gather_facts: no
  become: True
  roles:
    - python

- name: Configure instance(s)
  hosts: all
  become: True
  gather_facts: True
  roles:
    - role: swapfile
      when: SWAPFILE_SIZE is defined and SWAPFILE_SIZE != ''
    - role: nginx
      nginx_sites:
      - certs
      - cms
      - lms
      - forum
      - xqueue
      nginx_default_sites:
      - lms
    - role: edxlocal
    - role: memcache
    - role: mongo
    - role: rabbitmq
      rabbitmq_ip: 127.0.0.1
    - role: oraclejdk
    - role: elasticsearch
    - role: edxapp
      celery_worker: True
    - role: edxapp
    - role: ecommerce
      when: SANDBOX_ENABLE_ECOMMERCE is defined and SANDBOX_ENABLE_ECOMMERCE
    - role: ecomworker
      ECOMMERCE_WORKER_BROKER_HOST: 127.0.0.1
      when: SANDBOX_ENABLE_ECOMMERCE is defined and SANDBOX_ENABLE_ECOMMERCE
    - role: rg_instructor_analytics_log_collector
      when: "{{ EDXAPP_RG_INSTRUCTOR_ANALYTICS_ENABLE | default(False) }}"
    - role: celerybeat
      when: EDXAPP_CELERY_BEAT.enabled | default(False)
    - role: analytics_api
      when: SANDBOX_ENABLE_ANALYTICS_API is defined and SANDBOX_ENABLE_ANALYTICS_API
    - role: insights
      when: SANDBOX_ENABLE_INSIGHTS is defined and SANDBOX_ENABLE_INSIGHTS
    # not ready yet: - edx_notes_api
    - role: demo
    - role: oauth_client_setup
    - role: forum
    - role: notifier
    - role: xqueue
      update_users: True
    - role: certs
    - role: newrelic
      when: COMMON_ENABLE_NEWRELIC
    - role: datadog
      when: COMMON_ENABLE_DATADOG
