---

# Example sandbox configuration
# for single server community
# installs

- name: Bootstrap instance(s)
  hosts: mongo
  gather_facts: no
  become: True
  roles:
    - python

- name: Configure instance(s)
  hosts: all
  become: True
  gather_facts: True
  roles:
    - role: mongo
    - role: datadog
      when: COMMON_ENABLE_DATADOG
