---

  database_connection: &default_connection
    login_host: "{{ endpoint }}"
    login_user: "{{ EDXAPP_MYSQL_USER_ADMIN }}"
    login_password: "{{ EDXAPP_MYSQL_PASSWORD_ADMIN }}"

  databases:
    - name: "{{ EDXAPP_MYSQL_DB_NAME }}"
      state: "present"
      encoding: "utf8"
      <<: *default_connection
    
    - name: "{{ EDXAPP_MYSQL_CSMH_DB_NAME }}"
      state: "present"
      encoding: "utf8"
      <<: *default_connection
    
    - name: "{{ XQUEUE_MYSQL_DB_NAME }}"
      state: "present"
      encoding: "utf8"
      <<: *default_connection

    - name: "{{ INSIGHTS_DATABASE_NAME }}"
      state: "present"
      encoding: "utf8"
      <<: *default_connection
    
    - name: "{{ ANALYTICS_API_DEFAULT_DB_NAME }}"
      state: "present"
      encoding: "utf8"
      <<: *default_connection

    - name: "{{ ANALYTICS_API_REPORTS_DB_NAME }}"
      state: "present"
      encoding: "utf8"
      <<: *default_connection


  database_users:
    - name: "{{ COMMON_MYSQL_MIGRATE_USER }}"
      state: "present"
      password: "{{ COMMON_MYSQL_MIGRATE_PASS }}"
      host: "%"
      privileges:
        - '{{ EDXAPP_MYSQL_DB_NAME }}.*:ALL'
        - '{{ EDXAPP_MYSQL_CSMH_DB_NAME }}.*:ALL'
      <<: *default_connection
    
    - name: "{{ COMMON_MYSQL_MIGRATE_USER }}"
      state: "present"
      password: "{{ COMMON_MYSQL_MIGRATE_PASS }}"
      host: "%"
      privileges:
        - '{{ EDXAPP_MYSQL_DB_NAME }}.*:ALL'
        - '{{ EDXAPP_MYSQL_CSMH_DB_NAME }}.*:ALL'
      <<: *default_connection
    
    - name: "{{ COMMON_MYSQL_MIGRATE_USER }}"
      state: "present"
      password: "{{ COMMON_MYSQL_MIGRATE_PASS }}"
      host: "%"
      privileges:
        - '{{ EDXAPP_MYSQL_DB_NAME }}.*:ALL'
        - '{{ EDXAPP_MYSQL_CSMH_DB_NAME }}.*:ALL'
      <<: *default_connection
    
    - name: "{{ COMMON_MYSQL_MIGRATE_USER }}"
      state: "present"
      password: "{{ COMMON_MYSQL_MIGRATE_PASS }}"
      host: "%"
      privileges:
        - '{{ XQUEUE_MYSQL_DB_NAME }}.*:ALL'
      <<: *default_connection
    
    - name: "{{ COMMON_MYSQL_MIGRATE_USER }}"
      state: "present"
      password: "{{ COMMON_MYSQL_MIGRATE_PASS }}"
      host: "%"
      privileges:
        - '{{ INSIGHTS_DATABASE_NAME }}.*:ALL'
        - '{{ ANALYTICS_API_DEFAULT_DB_NAME }}.*:ALL'
        - '{{ ANALYTICS_API_REPORTS_DB_NAME }}.*:ALL'
      <<: *default_connection
    
    - name: "{{ EDXAPP_MYSQL_USER }}"
      state: "present"
      password: "{{ EDXAPP_MYSQL_PASSWORD }}"
      host: "%"
      privileges:
        - '{{EDXAPP_MYSQL_DB_NAME}}.*:ALL'
      <<: *default_connection
    
    - name: "{{ EDXAPP_MYSQL_USER }}"
      state: "present"
      password: "{{ EDXAPP_MYSQL_PASSWORD }}"
      host: "%"
      privileges:
        - '{{EDXAPP_MYSQL_DB_NAME}}.*:ALL'
      <<: *default_connection
    
    - name: "{{ EDXAPP_MYSQL_USER }}"
      state: "present"
      password: "{{ EDXAPP_MYSQL_PASSWORD }}"
      host: "%"
      privileges:
        - '{{EDXAPP_MYSQL_DB_NAME}}.*:ALL'
      <<: *default_connection
    
    - name: "{{ EDXAPP_MYSQL_USER }}"
      state: "present"
      password: "{{ EDXAPP_MYSQL_PASSWORD }}"
      host: "%"
      privileges:
        - '{{EDXAPP_MYSQL_DB_NAME}}.*:ALL'
      <<: *default_connection
    
    - name: "{{ XQUEUE_MYSQL_USER }}"
      state: "present"
      password: "{{ XQUEUE_MYSQL_PASSWORD }}"
      host: "%"
      privileges:
        - '{{XQUEUE_MYSQL_DB_NAME}}.*:ALL'
      <<: *default_connection
    
    - name: "{{ SECRET_INSIGHTS_DATABASES_USERNAME }}"
      state: "present"
      password: "{{ SECRET_INSIGHTS_DATABASES_PASSWORD }}"
      host: "%"
      privileges:
        - "{{ INSIGHTS_DATABASE_NAME }}.*:ALL"
      <<: *default_connection
    
    - name: "{{ ANALYTICS_API_DATABASE_DEFAULT_USERNAME }}"
      state: "present"
      password: "{{ ANALYTICS_API_DATABASE_DEFAULT_PASSWORD }}"
      host: "%"
      privileges:
        - "{{ ANALYTICS_API_DEFAULT_DB_NAME }}.*:ALL"
      <<: *default_connection

    - name: "{{ ANALYTICS_API_DATABASE_REPORTS_USERNAME }}"
      state: "present"
      password: "{{ ANALYTICS_API_DATABASE_REPORTS_PASSWORD }}"
      host: "%"
      privileges:
        - "{{ ANALYTICS_API_REPORTS_DB_NAME }}.*:ALL"
      <<: *default_connection

    - name: "{{ ANALYTICS_MYSQL_RO_USERNAME }}"
      state: "present"
      password: "{{ ANALYTICS_MYSQL_RO_PASSWORD }}"
      host: "%"
      privileges:
        - "{{ EDXAPP_MYSQL_DB_NAME }}.*:SELECT"
      <<: *default_connection
        
    - name: "{{ COMMON_MYSQL_READ_ONLY_USER }}"
      state: "present"
      password: "{{ COMMON_MYSQL_READ_ONLY_PASS }}"
      host: "%"
      privileges:
        - '*.*:SELECT,LOCK TABLES'
      <<: *default_connection
    
    - name: "{{ COMMON_MYSQL_ADMIN_USER }}"
      state: "present"
      password: "{{ COMMON_MYSQL_ADMIN_PASS }}"
      host: "%"
      privileges:
        - '*.*:CREATE USER'
      <<: *default_connection

