---
- hosts: edx
  become: true
  become_method: sudo
  become_user: root
  gather_facts: True
  vars:
    service_variants_enabled:
      - cms
      - lms
    migrate_db: "yes"

  roles:
    - role: nginx
      nginx_sites:
      - cms
      - lms
      nginx_default_sites:
      - lms
      CMS_HOSTNAME: "{{ EDXAPP_CMS_SITE_NAME }}" 
    - edxapp

- hosts: edx
  become: true
  become_method: sudo
  become_user: root
  gather_facts: True
  vars:
    service_variants_enabled:
      - cms
      - lms
    EDXAPP_WORKERS:
      cms: 4
      lms: 16
  roles:
    - { role: 'edxapp', celery_worker: True, celery_cms_worker: True, celery_lms_worker: True}

