
- name: "Set short version name"
  set_fact:
    zabbix_short_version: "{{ zabbix_version | regex_replace('\\.', '') }}"

- name: "Install gpg key"
  apt_key:
    id: "{{ sign_keys[zabbix_short_version][ansible_distribution_release]['sign_key'] }}"
    url: http://repo.zabbix.com/zabbix-official-repo.key
  become: yes

- name: "Installing deb-src repository Ubuntu"
  apt_repository:
    repo: "deb-src http://repo.zabbix.com/zabbix/{{ zabbix_version }}/ubuntu/ {{ ansible_distribution_release }} main"
    state: present
  when:
    - ansible_distribution == "Ubuntu"
  become: yes

- name: "Installing deb repository Ubuntu"
  apt_repository:
    repo: "deb http://repo.zabbix.com/zabbix/{{ zabbix_version }}/ubuntu/ {{ ansible_distribution_release }} main"
    state: present
  when:
    - ansible_distribution == "Ubuntu"
  become: yes

# Note: set cache_valid_time=0 to ensure that an apt-get update after the added repo-key
# else you often get 'WARNING: The following packages cannot be authenticated!
# See also: http://askubuntu.com/questions/75565/why-am-i-getting-authentication-errors-for-packages-from-an-ubuntu-repository
- name: "Installing zabbix-agent"
  apt:
    pkg: zabbix-agent
    state: "{{ zabbix_agent_package_state }}"
    update_cache: yes
    cache_valid_time: 0
  become: yes

- name: "Enable the service"
  service:
    name: zabbix-agent
    enabled: yes
    use: service
  become: yes

